name: Deploy helper app to GitHub Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'helper-app/**'
      - '.github/workflows/gh-pages.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Pages content
        run: |
          set -e
          mkdir -p site
          cp -R helper-app/* site/
          # Copy sample JSON files to be accessible at site root
          if [ -f config.json.sample ]; then cp -v config.json.sample site/; fi
          if [ -f sun_times.json.sample ]; then cp -v sun_times.json.sample site/; fi

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
